const STORAGE_KEY='simids_tanjung_lago_v6d';
const LEGACY_STORAGE_KEYS=['simids_tanjung_lago_v5','simids_tanjung_lago_v4','simids_tanjung_lago_v3','simids_tanjung_lago_v2'];
const REMINDER_SEEN_KEY='simids_tanjung_lago_reminder_seen';
const VACCINES=[
{id:'HB0',label:'HB0',excel:false,input:true},{id:'HB0_24',label:'HB0 (<24 Jam)',excel:true},{id:'HB0_1_7',label:'HB0 (1-7 Hari)',excel:true},{id:'HB0_TOTAL',label:'HB0 (Total)',excel:true,computed:true},{id:'BCG',label:'BCG',excel:true},{id:'OPV1',label:'OPV-1',excel:true},{id:'DPT_HB_HIB1',label:'DPT/HB-Hib-1',excel:true},{id:'HEXA1',label:'DPT/HB-Hib-IPV (Heksavalen)-1',excel:true},{id:'OPV2',label:'OPV-2',excel:true},{id:'PCV1',label:'Pneumokokus-1',excel:true},{id:'ROTA1',label:'Rotavirus-1',excel:true},{id:'DPT_HB_HIB2',label:'DPT/HB-Hib-2',excel:true},{id:'HEXA2',label:'DPT/HB-Hib-IPV (Heksavalen)-2',excel:true},{id:'OPV3',label:'OPV-3',excel:true},{id:'PCV2',label:'Pneumokokus-2',excel:true},{id:'DPT_HB_HIB3',label:'DPT/HB-Hib-3',excel:true},{id:'HEXA3',label:'DPT/HB-Hib-IPV (Heksavalen)-3',excel:true},{id:'OPV4',label:'OPV-4',excel:true},{id:'IPV1',label:'IPV-1',excel:true},{id:'ROTA2',label:'Rotavirus-2',excel:true},{id:'ROTA3',label:'Rotavirus-3',excel:true},{id:'MR1',label:'Campak-Rubella (MR)-1',excel:true},{id:'IPV2',label:'IPV-2',excel:true},{id:'IPV3',label:'IPV-3 (Khusus DIY)',excel:true},{id:'IBL',label:'Imunisasi Bayi Lengkap',excel:true},{id:'MR2',label:'Campak-Rubella (MR)-2',excel:false,program:true}
];
const KOHORT_INPUT_IDS=['HB0','BCG','OPV1','OPV2','OPV3','OPV4','DPT_HB_HIB1','DPT_HB_HIB2','DPT_HB_HIB3','IPV1','IPV2','ROTA1','ROTA2','ROTA3','PCV1','PCV2','MR1','MR2'];
const SERVICE_PLACES=[...new Set(window.SIMIDS_INITIAL.events.map(e=>e.servicePlace).filter(Boolean))].sort();
const DEFAULT_AREA={province:'SUMATERA SELATAN',district:'KAB. BANYUASIN',subdistrict:'TANJUNG LAGO',puskesmas:'TANJUNG LAGO',puskesmasCode:'1011718 - TANJUNG LAGO'};
const TARGETS=[];
function uid(){return crypto.randomUUID()}
function today(){return new Date().toISOString().slice(0,10)}
function fmtDate(v){if(!v)return '-';return new Date(v+'T00:00:00').toLocaleDateString('id-ID',{day:'numeric',month:'short',year:'numeric'})}
function esc(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function diffDays(v){if(!v)return null;return Math.floor((new Date()-new Date(v+'T00:00:00'))/86400000)}
function normalizePhone(p=''){let x=String(p||'').replace(/\D/g,'');if(x.startsWith('0'))x='62'+x.slice(1);if(x&&!x.startsWith('62'))x='62'+x;return x}
function waLink(child,r){const ph=normalizePhone(child.phone);if(!ph)return'';const parent=child.parentName||'Bapak/Ibu';const when=r.due?` pada ${fmtDate(r.due)}`:'';const status=r.status==='overdue'?'jadwal imunisasi yang sudah terlewat':r.status==='due'?'jadwal imunisasi yang sudah dekat':'kelengkapan imunisasi MR-2';const msg=`Assalamu'alaikum ${parent}. Kami dari Posyandu mengingatkan ${status} untuk ${child.name}${when}. Mohon konfirmasi apakah dapat hadir ke Posyandu / layanan imunisasi. Terima kasih.`;return `https://wa.me/${ph}?text=${encodeURIComponent(msg)}`}
function greeting(){const h=new Date().getHours();return h<11?'Selamat pagi':h<15?'Selamat siang':h<18?'Selamat sore':'Selamat malam'}
function normalizeTargets(list=[]){
  const source=list.length?list:TARGETS;
  return source.map(t=>{
    const m=Number(t.male??t.localSurvivingMale??0),f=Number(t.female??t.localSurvivingFemale??0);
    return {...t,male:m,female:f,
      pusdatinBirthMale:Number(t.pusdatinBirthMale??m),pusdatinBirthFemale:Number(t.pusdatinBirthFemale??f),
      pusdatinSurvivingMale:Number(t.pusdatinSurvivingMale??m),pusdatinSurvivingFemale:Number(t.pusdatinSurvivingFemale??f),
      localBirthMale:Number(t.localBirthMale??m),localBirthFemale:Number(t.localBirthFemale??f),
      localSurvivingMale:Number(t.localSurvivingMale??m),localSurvivingFemale:Number(t.localSurvivingFemale??f)
    };
  });
}
let state=window.SIMIDS_INITIAL;
state.targets=normalizeTargets(state.targets);
let selectedRiskHamlet='';
let saving=false;
async function save(action='update'){
  if(saving)return false;
  saving=true;updateConnection();
  const shield=document.createElement('div');shield.setAttribute('role','status');shield.textContent='Menyimpan ke database…';shield.style.cssText='position:fixed;inset:0;background:#ffffffbb;z-index:10000;display:grid;place-items:center;font-weight:700';document.body.appendChild(shield);
  try{await SimidsBackend.save(state,action);renderAll();return true}
  catch(error){state=SimidsBackend.rollback();state.targets=normalizeTargets(state.targets);renderAll();alert('Belum tersimpan: '+error.message);return false}
  finally{saving=false;shield.remove();updateConnection()}
}
document.addEventListener('submit',async e=>{if(saving){e.preventDefault();e.stopImmediatePropagation()}},true);
function toast(msg){const el=document.getElementById('toast');el.textContent=msg;el.classList.add('show');clearTimeout(window.__t);window.__t=setTimeout(()=>el.classList.remove('show'),2500)}
let eventIndex=new Map(),vaccineIndex=new Map(),childIndex=new Map();
function indexEvents(){eventIndex=new Map();vaccineIndex=new Map();childIndex=new Map(state.children.map(c=>[c.id,c]));state.events.forEach(e=>{if(!eventIndex.has(e.childId))eventIndex.set(e.childId,[]);eventIndex.get(e.childId).push(e);if(!vaccineIndex.has(e.vaccineId))vaccineIndex.set(e.vaccineId,[]);vaccineIndex.get(e.vaccineId).push(e)})}
function childEvents(id){return [...(eventIndex.get(id)||[])]}
function hasVaccine(id,v){return childEvents(id).some(e=>e.vaccineId===v)}
function latestDue(id){return [...childEvents(id)].filter(e=>e.nextDueDate).sort((a,b)=>b.date.localeCompare(a.date))[0]?.nextDueDate||''}
function getVaccine(id){return VACCINES.find(v=>v.id===id)||{label:id}}
function risk(child){const due=latestDue(child.id),d=diffDays(due),mr2=!hasVaccine(child.id,'MR2');if(due&&d>0)return{status:'overdue',label:`Jadwal lewat ${d} hari`,due};if(due&&d>=-state.settings.warningDays)return{status:'due',label:'Jadwal sudah dekat',due};if(mr2)return{status:'mr2',label:'MR-2 belum tercatat',due};return{status:'ok',label:'Terpantau',due}}
function pct(n,d){return d?Math.round(n/d*1000)/10:0}
function focusKids(){return state.children.filter(c=>c.village===state.settings.focusVillage)}
function fillVillage(id,all=false){const el=document.getElementById(id);if(!el)return;const current=el.value;el.innerHTML=(all?'<option value="all">Semua desa</option>':'')+state.targets.map(t=>`<option value="${esc(t.name)}">${esc(t.name)}</option>`).join('');if([...el.options].some(o=>o.value===current))el.value=current;else if(!all)el.value=state.settings.focusVillage}
/*xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx*/
function fillServicePlaces(){['childPosyandu','eventServicePlace'].forEach(id=>{const el=document.getElementById(id);if(!el)return;const cur=el.value;el.innerHTML='<option value="">Pilih / cari pos imunisasi</option>'+SERVICE_PLACES.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('');if([...el.options].some(o=>o.value===cur))el.value=cur})}
function prefillServicePlaceForChild(childId){const c=state.children.find(x=>x.id===childId),el=document.getElementById('eventServicePlace');if(!el||!c)return;const last=[...childEvents(childId)].filter(e=>e.servicePlace).sort((a,b)=>(b.date||'').localeCompare(a.date||''))[0];const value=c.posyandu||last?.servicePlace||'';if(value&&[...el.options].some(o=>o.value===value))el.value=value;refreshSearchableButtons()}
function fillChild(){const el=document.getElementById('eventChild');const current=el.value;el.innerHTML='<option value="">-- Pilih anak --</option>'+[...state.children].sort((a,b)=>a.name.localeCompare(b.name)).map(c=>`<option value="${c.id}">${esc(c.name)} — ${esc(c.parentName)}</option>`).join('');if([...el.options].some(o=>o.value===current))el.value=current}
function fillVaccines(){const el=document.getElementById('eventVaccine');const current=el.value;el.innerHTML='<option value="">-- Pilih jenis imunisasi --</option>'+VACCINES.filter(v=>!v.computed).map(v=>`<option value="${v.id}">${esc(v.label)}</option>`).join('');if([...el.options].some(o=>o.value===current))el.value=current}
function showPage(name){document.querySelectorAll('.page').forEach(p=>p.classList.toggle('active',p.id===`page-${name}`));document.querySelectorAll('.nav-btn,.bottom-nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.page===name));document.getElementById('sideNav').classList.remove('open');window.scrollTo({top:0,behavior:'smooth'})}
document.body.addEventListener('click',e=>{const n=e.target.closest('[data-page]');if(n)showPage(n.dataset.page);const j=e.target.closest('[data-jump]');if(j)showPage(j.dataset.jump)});
document.getElementById('mobileMenuBtn').onclick=()=>document.getElementById('sideNav').classList.toggle('open');

function renderRole(){const role=state.settings.role||'kader';document.getElementById('roleSelect').value=role;document.querySelectorAll('.advanced-nav').forEach(x=>x.style.display=role==='kader'?'none':'');document.querySelectorAll('.admin-nav').forEach(x=>x.style.display=role==='puskesmas'?'grid':'none');const rt=document.getElementById('sideRoleText');if(rt)rt.textContent=role==='kader'?'Kader Posyandu':role==='bidan'?'Bidan Desa':'Puskesmas / Admin';document.getElementById('validationInfo').innerHTML=role==='kader'?'Data yang Ibu simpan akan <b>diperiksa oleh bidan</b>. Tanggal input disimpan otomatis.':'Entri dari bidan dapat langsung divalidasi setelah disimpan.'}
function renderHome(){
  document.getElementById('todayText').textContent=new Date().toLocaleDateString('id-ID',{weekday:'long',day:'numeric',month:'long',year:'numeric'});
  const gt=document.getElementById('greetingText');if(gt)gt.textContent=(greeting()+' • KADER POSYANDU').toUpperCase();
  const kids=focusKids(),risks=kids.map(risk),over=risks.filter(r=>r.status==='overdue').length,due=risks.filter(r=>r.status==='due').length,unvalidated=state.events.filter(e=>!e.validated).length,mr2=kids.filter(c=>hasVaccine(c.id,'MR2')).length;
  document.getElementById('homeSummary').innerHTML=[['Anak terdaftar',kids.length],['Jadwal lewat',over],['Jadwal dekat',due],['Cakupan MR-2',pct(mr2,kids.length)+'%']].map(([l,v])=>`<div class="summary-box"><b>${v}</b><span>${l}</span></div>`).join('');
  const total=over+due;
  const banner=document.getElementById('homeReminderBanner');
  if(banner){banner.classList.toggle('safe',!total);banner.innerHTML=total?`<div class="reminder-banner-icon">🔔</div><div class="reminder-banner-copy"><b>${over?`${over} anak perlu segera dihubungi`:''}${over&&due?' • ':''}${due?`${due} jadwal sudah dekat`:''}</b><span>Tekan tombol untuk membuka daftar dan pesan WhatsApp yang sudah disiapkan.</span></div><button class="btn light" id="homeOpenReminder">Lihat pengingat</button>`:`<div class="reminder-banner-icon">✓</div><div class="reminder-banner-copy"><b>Tidak ada pengingat mendesak hari ini</b><span>Silakan lanjutkan pencatatan pelayanan rutin.</span></div><button class="btn secondary" data-jump="immunization">Catat imunisasi</button>`;}
  const tasks=[];
  if(over)tasks.push([`${over} anak jadwalnya sudah lewat`,'Hubungi orang tua terlebih dahulu','followup']);
  if(due)tasks.push([`${due} anak jadwalnya sudah dekat`,'Beri pengingat sebelum jadwal terlewat','followup']);
  if(unvalidated&&state.settings.role!=='kader')tasks.push([`${unvalidated} input menunggu validasi`,'Periksa input kader','dashboard']);
  if(!tasks.length)tasks.push(['Semua pengingat sudah aman','Lanjutkan pencatatan pelayanan rutin','immunization']);
  document.getElementById('todayTasks').innerHTML=tasks.map(([a,b,p],i)=>`<div class="task-item"><div><b>${i+1}. ${esc(a)}</b><small>${esc(b)}</small></div><button class="mini-btn primary" data-jump="${p}">Buka</button></div>`).join('');
  updateReminderBadges();
}
function renderChildren(){const q=document.getElementById('childSearch').value.trim().toLowerCase(),v=document.getElementById('childVillageFilter').value||'all';let arr=state.children.filter(c=>(v==='all'||c.village===v)&&(!q||(c.name+' '+(c.nik||'')+' '+c.parentName).toLowerCase().includes(q))).sort((a,b)=>a.name.localeCompare(b.name));document.getElementById('childrenCards').innerHTML=arr.length?arr.map(c=>{const r=risk(c);return `<div class="record-card"><div class="record-main"><b>${esc(c.name)} <span class="tag ${r.status==='ok'?'good':r.status==='overdue'?'danger':'warn'}">${esc(r.label)}</span></b><small>${esc(c.parentName)} • ${esc(c.village)} / ${esc(c.hamlet)} • ${c.sex==='L'?'Laki-laki':'Perempuan'}</small></div><div class="record-actions"><button class="mini-btn primary" data-quick-immunize="${c.id}">💉 Imunisasi</button><button class="mini-btn" data-edit-child="${c.id}">Ubah</button></div></div>`}).join(''):'<div class="empty">Data anak tidak ditemukan.</div>'}
function renderSelectedChild(){const id=document.getElementById('eventChild').value,c=state.children.find(x=>x.id===id),el=document.getElementById('selectedChildPreview');if(!c){el.innerHTML='<span class="preview-icon">ℹ</span><span>Pilih anak terlebih dahulu. Riwayat terakhir akan muncul di sini.</span>';syncImmunizationPickerLabels();renderImmunizationReview();return}const ev=childEvents(id).sort((a,b)=>b.date.localeCompare(a.date));el.innerHTML=`<span class="preview-icon">✓</span><div class="preview-main"><b>${esc(c.name)} • ${esc(c.parentName)}</b><span>${esc(c.hamlet||'-')} • ${esc(c.posyandu||'Posyandu belum diisi')}</span><span>${ev.length?`Terakhir: ${esc(getVaccine(ev[0].vaccineId).label)} (${fmtDate(ev[0].date)})`:'Belum ada riwayat imunisasi di sistem.'}</span></div>`;syncImmunizationPickerLabels();renderImmunizationReview()}
function renderRecentEvents(){let arr=[...state.events].sort((a,b)=>(b.createdAt||b.date).localeCompare(a.createdAt||a.date)).slice(0,8);document.getElementById('recentEvents').innerHTML=arr.length?arr.map(e=>{const c=state.children.find(x=>x.id===e.childId);if(!c)return'';return `<div class="record-card"><div class="record-main"><b>${esc(c.name)} — ${esc(getVaccine(e.vaccineId).label)}</b><small>${fmtDate(e.date)} • ${esc(e.servicePlace||c.posyandu||c.village)} • input ${fmtDate(e.inputDate)} • ${e.sourceImport?'Sumber: kohort Excel':e.validated?'Sudah divalidasi':'Menunggu validasi'}</small></div><div class="record-actions">${e.validated?'<span class="tag good">Valid</span>':'<span class="tag warn">Menunggu</span>'}</div></div>`}).join(''):'<div class="empty">Belum ada input imunisasi.</div>'}
function riskList(){return state.children.map(c=>({c,r:risk(c)})).filter(x=>x.r.status!=='ok')}
function renderFollowup(){
  const vf=document.getElementById('riskVillageFilter').value||'all',sf=document.getElementById('riskStatusFilter').value||'all';
  const all=riskList().filter(x=>vf==='all'||x.c.village===vf);
  const over=all.filter(x=>x.r.status==='overdue').length,due=all.filter(x=>x.r.status==='due').length,mr2=all.filter(x=>x.r.status==='mr2').length;
  document.getElementById('riskSummary').innerHTML=[['Segera hubungi',over],['Jadwal dekat',due],['MR-2 belum tercatat',mr2]].map(([l,v])=>`<div class="risk-box"><b>${v}</b><span>${l}</span></div>`).join('');
  const mapItems=state.children.filter(c=>vf==='all'||c.village===vf).map(c=>({c,r:risk(c)}));
  const groups={};mapItems.forEach(x=>{const h=x.c.hamlet||'Dusun belum diisi';groups[h]=groups[h]||[];groups[h].push(x)});
  const entries=Object.entries(groups).sort((a,b)=>a[0].localeCompare(b[0],'id'));
  const map=document.getElementById('riskMap');
  if(map){map.className=`risk-map ${entries.length===4?'risk-map-four':''}`;map.innerHTML=entries.length?entries.map(([h,arr],i)=>{const o=arr.filter(x=>x.r.status==='overdue').length,d=arr.filter(x=>x.r.status==='due').length,m=arr.filter(x=>x.r.status==='mr2').length,priority=o+d+m,score=o*3+d*2+m;const lvl=(o>=2||score>=6)?'high':score>=2?'medium':'low';return `<button type="button" class="risk-zone ${lvl} ${selectedRiskHamlet===h?'selected':''} zone-${(i%4)+1}" data-risk-hamlet="${esc(h)}"><span class="risk-zone-name">${esc(h)}</span><strong>${priority}</strong><span class="risk-zone-status">${lvl==='high'?'Prioritas tinggi':lvl==='medium'?'Perlu perhatian':priority?'Risiko lebih rendah':'Tidak ada pengingat'}</span><small>${o} lewat • ${d} dekat • ${m} MR-2 • ${arr.length} anak</small></button>`}).join(''):'<div class="empty">Belum ada risiko yang perlu dipetakan.</div>'}
  const active=document.getElementById('riskHamletActive');if(active){active.innerHTML=selectedRiskHamlet?`Menampilkan daftar dari <b>${esc(selectedRiskHamlet)}</b> <button type="button" class="link-btn" data-risk-reset>× Tampilkan semua</button>`:'Sentuh salah satu dusun pada peta untuk memfilter daftar anak.'}
  let list=all.filter(x=>(sf==='all'||x.r.status===sf)&&(!selectedRiskHamlet||x.c.hamlet===selectedRiskHamlet)).sort((a,b)=>({overdue:0,due:1,mr2:2}[a.r.status]-({overdue:0,due:1,mr2:2}[b.r.status])));
  document.getElementById('followupList').innerHTML=list.length?list.map(({c,r})=>{const wa=waLink(c,r),last=[...state.followups].filter(f=>f.childId===c.id).sort((a,b)=>b.date.localeCompare(a.date))[0];return `<div class="record-card"><div class="record-main"><b>${esc(c.name)} <span class="tag ${r.status==='overdue'?'danger':r.status==='due'?'warn':'neutral'}">${esc(r.label)}</span></b><small>${esc(c.parentName)} • ${esc(c.hamlet)}${r.due?` • Jadwal: ${fmtDate(r.due)}`:''}${last?`<br>Terakhir: ${outcomeLabel(last.outcome)} (${fmtDate(last.date)})`:''}</small></div><div class="record-actions">${wa?`<a class="mini-btn wa-btn" href="${wa}" target="_blank" rel="noopener">💬 Kirim WhatsApp</a>`:'<span class="tag neutral">No. WA belum diisi</span>'}<button class="mini-btn primary" data-followup="${c.id}">✓ Catat hasil</button></div></div>`}).join(''):'<div class="empty">Tidak ada anak pada filter ini.</div>';
}
function outcomeLabel(v){return({contacted:'Sudah dihubungi',scheduled:'Sudah dijadwalkan',visited:'Sudah dikunjungi',immunized:'Sudah diimunisasi',refused:'Menolak/belum bersedia',unreachable:'Belum dapat dihubungi'})[v]||v}
function assessmentStats(){const a=state.assessments;if(!a.length)return{n:0,pre:0,post:0,improve:0};const pre=a.reduce((s,x)=>s+Number(x.pre),0)/a.length,post=a.reduce((s,x)=>s+Number(x.post),0)/a.length;return{n:a.length,pre,post,improve:pre?((post-pre)/pre*100):0}}
function renderEducation(){const hist=[...state.education].sort((a,b)=>b.date.localeCompare(a.date)).slice(0,8);document.getElementById('educationHistory').innerHTML=hist.length?hist.map(x=>`<div class="record-card"><div class="record-main"><b>${eduTypeLabel(x.type)} — ${esc(x.topic)}</b><small>${fmtDate(x.date)} • ${esc(x.village)} ${x.hamlet?' / '+esc(x.hamlet):''} • ${x.participants} peserta</small></div></div>`).join(''):'<div class="empty">Belum ada kegiatan edukasi.</div>';const s=assessmentStats();document.getElementById('assessmentSummary').innerHTML=`<b>Evaluasi pre/post-test:</b> ${s.n} peserta • Rata-rata pre ${s.pre.toFixed(1)} • post ${s.post.toFixed(1)} • peningkatan <b>${s.improve.toFixed(1)}%</b>. Target proposal: peningkatan ≥30%.`}
function eduTypeLabel(v){return({ibu:'Penyuluhan Ibu Balita',kader_risk:'Pelatihan Komunikasi Risiko',kader_digital:'Pelatihan Operasional Digital',peer:'Kelompok Peduli Imunisasi'})[v]||v}
function validatedVaccineBy(childId,vaccineId,endDate='9999-12-31'){
  return childEvents(childId).some(e=>e.vaccineId===vaccineId&&e.validated!==false&&e.date<=endDate)
}
function renderDashboard(){
  const kids=focusKids(),mr1=kids.filter(c=>validatedVaccineBy(c.id,'MR1')).length,mr2=kids.filter(c=>validatedVaccineBy(c.id,'MR2')).length,over=kids.map(risk).filter(r=>r.status==='overdue').length,unv=state.events.filter(e=>!e.validated).length,s=assessmentStats();
  document.getElementById('programKpis').innerHTML=[['Anak terdaftar',kids.length],['MR-1',pct(mr1,kids.length)+'%'],['MR-2',pct(mr2,kids.length)+'%'],['Perlu sweeping',over],['Menunggu validasi',unv]].map(([l,v])=>`<div class="kpi-card"><b>${v}</b><span>${l}</span></div>`).join('');
  renderCoverageTrend();
  document.getElementById('coverageBars').innerHTML=['BCG','MR1','MR2','IBL'].map(id=>{const n=kids.filter(c=>validatedVaccineBy(c.id,id)).length,p=pct(n,kids.length);return `<div class="coverage-row"><div class="top"><span>${esc(getVaccine(id).label)}</span><b>${p}%</b></div><div class="bar-track"><div class="bar-fill" style="width:${Math.min(100,p)}%"></div></div></div>`}).join('');
  const eduParticipants=state.education.filter(e=>e.type==='ibu').reduce((s,e)=>s+Number(e.participants||0),0),trained=new Set(state.assessments.filter(a=>a.type==='kader'&&Number(a.post)>=70).map(a=>a.name)).size,swept=new Set(state.followups.filter(f=>['visited','immunized','scheduled'].includes(f.outcome)).map(f=>f.childId)).size;const ibuAssessed=state.assessments.filter(a=>a.type==='ibu').length;const dusunEdukasi=new Set(state.education.filter(e=>e.type==='ibu'&&e.hamlet).map(e=>e.hamlet)).size;const latest=state.events.filter(e=>e.validated!==false).map(e=>e.date).sort().at(-1);const delay=latest?diffDays(latest):999;
  const targets=[['Pre-test ibu balita','≥90 responden',ibuAssessed>=90],['Penyuluhan ibu balita','≥100 peserta & 4 dusun',eduParticipants>=100&&dusunEdukasi>=4],['Kader lulus operasional','≥7 dari 8 kader, nilai ≥70',trained>=7],['Kohort masuk sistem','187 balita',kids.length>=187],['Sweeping MR-2','≥22 anak',swept>=22],['Peningkatan pengetahuan','≥30%',s.improve>=30],['Keterlambatan data','≤7 hari',delay<=7],['Cakupan MR-2 akhir','≥85%',pct(mr2,kids.length)>=85]];
  document.getElementById('proposalTargets').innerHTML=targets.map(([a,b,ok])=>`<div class="target-card"><b>${a}</b><small>${b}</small><div class="target-status"><span class="tag ${ok?'good':'warn'}">${ok?'Tercapai':'Belum tercapai'}</span></div></div>`).join('');
  const q=state.events.filter(e=>!e.validated).slice(0,20);document.getElementById('validationQueue').innerHTML=q.length?q.map(e=>{const c=state.children.find(x=>x.id===e.childId);return `<div class="record-card"><div class="record-main"><b>${esc(c?.name||'-')} — ${esc(getVaccine(e.vaccineId).label)}</b><small>${fmtDate(e.date)} • ${esc(c?.hamlet||'')}</small></div><div class="record-actions"><button class="mini-btn good" data-validate="${e.id}">✓ Validasi</button></div></div>`}).join(''):'<div class="empty">Tidak ada data menunggu validasi.</div>'
}
function renderCoverageTrend(){
  const el=document.getElementById('weeklyTrend');if(!el)return;
  const vaccineId=document.getElementById('trendVaccineSelect')?.value||'MR2',kids=focusKids(),n=8,now=new Date(),points=[];
  for(let i=n-1;i>=0;i--){const d=new Date(now);d.setHours(23,59,59,999);d.setDate(now.getDate()-i*7);const iso=d.toISOString().slice(0,10);const count=kids.filter(c=>validatedVaccineBy(c.id,vaccineId,iso)).length;points.push({date:iso,count,p:pct(count,kids.length)})}
  const W=720,H=255,L=44,R=18,T=22,B=45,plotW=W-L-R,plotH=H-T-B,x=(i)=>L+(points.length===1?0:i*(plotW/(points.length-1))),y=(v)=>T+(100-Math.max(0,Math.min(100,v)))/100*plotH;
  const poly=points.map((p,i)=>`${x(i)},${y(p.p)}`).join(' '),grid=[0,25,50,75,100];
  const threshold=vaccineId==='MR2'?`<line x1="${L}" y1="${y(85)}" x2="${W-R}" y2="${y(85)}" class="trend-threshold"/><text x="${W-R-3}" y="${y(85)-6}" text-anchor="end" class="trend-threshold-label">Target 85%</text>`:'';
  el.innerHTML=`<div class="trend-chart-wrap"><svg class="trend-svg" viewBox="0 0 ${W} ${H}" role="img" aria-label="Tren cakupan mingguan ${esc(getVaccine(vaccineId).label)}">${grid.map(g=>`<line x1="${L}" y1="${y(g)}" x2="${W-R}" y2="${y(g)}" class="trend-grid"/><text x="${L-8}" y="${y(g)+4}" text-anchor="end" class="trend-axis">${g}%</text>`).join('')}${threshold}<polyline points="${poly}" class="trend-line"/>${points.map((p,i)=>`<circle cx="${x(i)}" cy="${y(p.p)}" r="5" class="trend-dot"/><text x="${x(i)}" y="${Math.max(15,y(p.p)-11)}" text-anchor="middle" class="trend-value">${p.p}%</text><text x="${x(i)}" y="${H-16}" text-anchor="middle" class="trend-date">${new Date(p.date+'T00:00:00').toLocaleDateString('id-ID',{day:'2-digit',month:'short'})}</text>`).join('')}</svg></div>`;
  const summary=document.getElementById('trendSummary');if(summary){const first=points[0]?.p||0,last=points.at(-1)?.p||0,diff=Math.round((last-first)*10)/10;summary.innerHTML=`<span><b>${esc(getVaccine(vaccineId).label)}</b></span><span>Awal periode <b>${first}%</b></span><span>Sekarang <b>${last}%</b></span><span>Perubahan <b>${diff>0?'+':''}${diff}%</b></span><small>Persentase kumulatif berdasarkan anak yang terdaftar di SiMIDS dan data yang sudah divalidasi.</small>`}
}
function targetKeys(){return ['pusdatinBirthMale','pusdatinBirthFemale','pusdatinSurvivingMale','pusdatinSurvivingFemale','localBirthMale','localBirthFemale','localSurvivingMale','localSurvivingFemale']}
function aggregateTarget(items){const out={name:'TOTAL',verified:items.length>0&&items.every(t=>t.verified)};targetKeys().forEach(k=>out[k]=items.reduce((a,t)=>a+Number(t[k]||0),0));out.male=out.localSurvivingMale;out.female=out.localSurvivingFemale;return out}
function getTarget(village){return village==='all'?aggregateTarget(state.targets):state.targets.find(t=>t.name===village)||normalizeTargets([{name:village,male:0,female:0}])[0]}
function eventIdsFor(vaccineId,village,month,sex){
  const codes=vaccineId==='HB0_TOTAL'?['HB0','HB0_24','HB0_1_7']:[vaccineId];
  const ids=new Set();
  for(const code of codes)for(const e of vaccineIndex.get(code)||[]){
    const c=childIndex.get(e.childId);
    if(c&&e.validated!==false&&(village==='all'||c.village===village)&&(!sex||c.sex===sex)&&Number(e.date.slice(0,4))===Number(state.settings.year)&&Number(e.date.slice(5,7))<=Number(month))ids.add(c.id);
  }
  return ids;
}
function vaccineReportStat(vaccineId,village,month,target=getTarget(village)){const m=eventIdsFor(vaccineId,village,month,'L').size,f=eventIdsFor(vaccineId,village,month,'P').size,n=m+f,dm=target.verified?Number(target.localSurvivingMale||0):0,df=target.verified?Number(target.localSurvivingFemale||0):0;return{m,f,n,pm:dm?pct(m,dm):"—",pf:df?pct(f,df):"—",pn:dm+df?pct(n,dm+df):"—"}}
function reportRows(village,month){const target=getTarget(village);return VACCINES.filter(v=>v.excel).map(v=>({label:v.label,...vaccineReportStat(v.id,village,month,target)}))}
function targetSummaryHtml(t){if(!t.verified)return '<div class="info-box">Sasaran resmi belum diverifikasi. Jumlah pelayanan ditampilkan; persentase sasaran belum tersedia.</div>';const blocks=[['Pusdatin • Bayi Baru Lahir',t.pusdatinBirthMale,t.pusdatinBirthFemale],['Pusdatin • Surviving Infants',t.pusdatinSurvivingMale,t.pusdatinSurvivingFemale],['Sasaran Daerah • Bayi Baru Lahir',t.localBirthMale,t.localBirthFemale],['Sasaran Daerah • Surviving Infants',t.localSurvivingMale,t.localSurvivingFemale]];return blocks.map(([l,m,f])=>`<div class="report-target-card"><span>${l}</span><div><b>${m+f}</b><small>L ${m} • P ${f}</small></div></div>`).join('')}
function excelHeaderHtml(){const vaccines=VACCINES.filter(v=>v.excel);return `<thead><tr class="excel-h1"><th rowspan="3">NO</th><th rowspan="3">PUSKESMAS</th><th rowspan="3">DESA</th><th colspan="6">SASARAN PUSDATIN</th><th colspan="6">SASARAN DAERAH</th><th colspan="${vaccines.length*6}">HASIL IMUNISASI BAYI</th></tr><tr class="excel-h2"><th colspan="3">BAYI BARU LAHIR</th><th colspan="3">SURVIVING INFANTS</th><th colspan="3">BAYI BARU LAHIR</th><th colspan="3">SURVIVING INFANTS</th>${vaccines.map(v=>`<th colspan="6">${esc(v.label)}</th>`).join('')}</tr><tr class="excel-h3">${'<th>L</th><th>P</th><th>JUMLAH</th>'.repeat(4)}${vaccines.map(()=>'<th># L</th><th>%</th><th># P</th><th>%</th><th># JML</th><th>%</th>').join('')}</tr></thead>`}
function excelRowData(target,index,month,total=false){const village=total?'all':target.name,vals=[total?'TOTAL':index+1,state.settings.puskesmas,total?'TOTAL':target.name,target.pusdatinBirthMale,target.pusdatinBirthFemale,target.pusdatinBirthMale+target.pusdatinBirthFemale,target.pusdatinSurvivingMale,target.pusdatinSurvivingFemale,target.pusdatinSurvivingMale+target.pusdatinSurvivingFemale,target.localBirthMale,target.localBirthFemale,target.localBirthMale+target.localBirthFemale,target.localSurvivingMale,target.localSurvivingFemale,target.localSurvivingMale+target.localSurvivingFemale];if(!target.verified)for(let j=3;j<15;j++)vals[j]='—';VACCINES.filter(v=>v.excel).forEach(v=>{const r=vaccineReportStat(v.id,village,month,target);vals.push(r.m,r.pm,r.f,r.pf,r.n,r.pn)});return vals}
function renderExcelReport(village,month){const table=document.getElementById('excelReportTable');if(!table)return;const selected=village==='all'?state.targets:state.targets.filter(t=>t.name===village);let body=selected.map((t,i)=>`<tr>${excelRowData(t,i,month,false).map((v,j)=>`<td>${j>14&&j%2===0?`${v}%`:esc(v)}</td>`).join('')}</tr>`).join('');if(village==='all'){const total=aggregateTarget(state.targets);body+=`<tr class="excel-total">${excelRowData(total,0,month,true).map((v,j)=>`<td>${j>14&&j%2===0?`${v}%`:esc(v)}</td>`).join('')}</tr>`}table.innerHTML=excelHeaderHtml()+`<tbody>${body}</tbody>`}
function renderReport(){
  const village=document.getElementById('reportVillageFilter').value||'all',month=Number(document.getElementById('reportMonthFilter').value||12),rows=reportRows(village,month),target=getTarget(village);
  document.getElementById('reportMeta').innerHTML=`<span class="meta-chip">Wilayah: <b>${village==='all'?'Semua desa':esc(village)}</b></span><span class="meta-chip">Sampai bulan: <b>${month}</b></span><span class="meta-chip">Tahun: <b>${state.settings.year}</b></span><span class="meta-chip">Data resmi: <b>sudah divalidasi</b></span>`;
  const ts=document.getElementById('reportTargetSummary');if(ts)ts.innerHTML=targetSummaryHtml(target);
  document.getElementById('reportTableBody').innerHTML=rows.map(r=>`<tr><td>${esc(r.label)}</td><td>${r.m}</td><td>${r.pm}%</td><td>${r.f}</td><td>${r.pf}%</td><td>${r.n}</td><td>${r.pn}%</td></tr>`).join('');
  renderExcelReport(village,month);
  const total=state.followups.length,im=state.followups.filter(f=>f.outcome==='immunized').length,visited=state.followups.filter(f=>f.outcome==='visited').length;document.getElementById('followupReport').innerHTML=`Total catatan tindak lanjut: <b>${total}</b> • dikunjungi: <b>${visited}</b> • tercatat sudah diimunisasi setelah tindak lanjut: <b>${im}</b>.`;
}
function renderSettings(){
  document.getElementById('settingPuskesmas').value=state.settings.puskesmas;document.getElementById('settingYear').value=state.settings.year;document.getElementById('settingFocusVillage').value=state.settings.focusVillage;document.getElementById('settingWarningDays').value=state.settings.warningDays;
  document.getElementById('targetMaster').innerHTML=state.targets.map(t=>!t.verified?`<div class="target-master-card"><b>${esc(t.name)}</b><p>Sasaran belum diverifikasi</p></div>`:`<div class="target-master-card"><div class="target-master-head"><b>${esc(t.name)}</b><span>${t.localSurvivingMale+t.localSurvivingFemale} sasaran</span></div><div class="target-master-grid"><span><small>Pusdatin BBL</small><b>L ${t.pusdatinBirthMale} • P ${t.pusdatinBirthFemale}</b></span><span><small>Pusdatin SI</small><b>L ${t.pusdatinSurvivingMale} • P ${t.pusdatinSurvivingFemale}</b></span><span><small>Daerah BBL</small><b>L ${t.localBirthMale} • P ${t.localBirthFemale}</b></span><span><small>Daerah SI</small><b>L ${t.localSurvivingMale} • P ${t.localSurvivingFemale}</b></span></div></div>`).join('')
}
function renderAll(){indexEvents();fillServicePlaces();['childVillage','eduVillage','assessmentVillage','settingFocusVillage'].forEach(id=>fillVillage(id));['childVillageFilter','riskVillageFilter','reportVillageFilter'].forEach(id=>fillVillage(id,true));fillChild();fillVaccines();renderRole();renderHome();renderChildren();renderSelectedChild();renderRecentEvents();renderFollowup();renderEducation();renderDashboard();renderReport();renderSettings();updateConnection();updateReminderBadges();refreshSearchableButtons();syncImmunizationPickerLabels();renderImmunizationReview()}
function updateConnection(){const el=document.getElementById('connectionBadge');el.className='status-badge '+(navigator.onLine?'good':'warn');el.textContent=saving?'● Menyimpan…':navigator.onLine?'● Terhubung Supabase':'● Offline — penyimpanan dinonaktifkan'}
window.addEventListener('online',updateConnection);window.addEventListener('offline',updateConnection);

// Pengingat otomatis di dalam website. Pesan WhatsApp hanya dibuka saat pengguna menekan tombol.
function reminderItems(){return riskList().filter(x=>['overdue','due','mr2'].includes(x.r.status)).sort((a,b)=>{const order={overdue:0,due:1,mr2:2};const d=order[a.r.status]-order[b.r.status];if(d)return d;return String(a.r.due||'').localeCompare(String(b.r.due||''))})}
function updateReminderBadges(){const n=reminderItems().length;['headerReminderCount','sideReminderCount','quickReminderCount','bottomReminderCount'].forEach(id=>{const el=document.getElementById(id);if(el){el.textContent=n;el.style.display=n?'grid':'none'}})}
function renderReminderCenter(){const items=reminderItems(),list=document.getElementById('reminderList'),title=document.getElementById('reminderTitle'),sub=document.getElementById('reminderSubtitle');if(!list)return;if(!items.length){title.textContent='Tidak ada pengingat mendesak';sub.textContent='Semua jadwal yang tercatat masih aman.';list.innerHTML='<div class="empty">✓ Tidak ada orang tua yang perlu dihubungi saat ini.</div>';return}const over=items.filter(x=>x.r.status==='overdue').length,due=items.filter(x=>x.r.status==='due').length,mr2=items.filter(x=>x.r.status==='mr2').length;title.textContent=`${items.length} anak perlu diperhatikan`;sub.textContent=`${over} jadwal lewat • ${due} jadwal dekat • ${mr2} MR-2 belum tercatat. Mulai dari yang paling atas.`;list.innerHTML=items.slice(0,5).map(({c,r})=>{const wa=waLink(c,r);return `<div class="reminder-item ${r.status==='overdue'?'urgent':''}"><div><b>${esc(c.name)}</b><small>${esc(c.parentName)} • ${esc(c.hamlet)}</small><span class="due-text ${r.status==='due'?'warn':''}">${esc(r.label)}${r.due?' • '+fmtDate(r.due):''}</span></div>${wa?`<a class="mini-btn wa-btn" href="${wa}" target="_blank" rel="noopener">💬 WhatsApp</a>`:'<span class="tag neutral">No. WA kosong</span>'}</div>`}).join('')+(items.length>5?`<div class="empty">+ ${items.length-5} anak lainnya. Tekan “Lihat semua pengingat”.</div>`:'')}
function openReminderCenter(manual=false){renderReminderCenter();document.getElementById('reminderModal').classList.add('open');document.getElementById('reminderModal').setAttribute('aria-hidden','false');if(!manual)localStorage.setItem(REMINDER_SEEN_KEY,today())}
function closeReminderCenter(markSeen=true){document.getElementById('reminderModal').classList.remove('open');document.getElementById('reminderModal').setAttribute('aria-hidden','true');if(markSeen)localStorage.setItem(REMINDER_SEEN_KEY,today())}
function maybeShowDailyReminder(){if(!reminderItems().length)return;if(localStorage.getItem(REMINDER_SEEN_KEY)===today())return;setTimeout(()=>openReminderCenter(false),650)}
document.getElementById('openReminderBtn').onclick=()=>openReminderCenter(true);
document.getElementById('closeReminderModal').onclick=()=>closeReminderCenter(true);
document.getElementById('reminderLaterBtn').onclick=()=>closeReminderCenter(true);
document.getElementById('reminderSeeAllBtn').onclick=()=>{closeReminderCenter(true);showPage('followup')};
document.body.addEventListener('click',e=>{if(e.target.closest('#homeOpenReminder'))openReminderCenter(true)});
document.getElementById('reminderModal').addEventListener('click',e=>{if(e.target.id==='reminderModal')closeReminderCenter(true)});

// Pemilih yang mudah dicari dan alur input imunisasi ramah kader
let vaccinePickerFilter='missing';
let genericSelectTarget=null;
const SEARCHABLE_SELECT_IDS=['childVillage','childPosyandu','eventServicePlace','childVillageFilter','riskVillageFilter','eduVillage','assessmentVillage','reportVillageFilter','settingFocusVillage'];
function foldText(v=''){return String(v).toLocaleLowerCase('id-ID').normalize('NFD').replace(/[\u0300-\u036f]/g,'')}
function fullDate(v){if(!v)return '-';return new Date(v+'T00:00:00').toLocaleDateString('id-ID',{weekday:'long',day:'numeric',month:'long',year:'numeric'})}
function latestEventTime(childId){const e=[...childEvents(childId)].sort((a,b)=>b.date.localeCompare(a.date))[0];return e?.date||''}
function pickerOpen(id){const el=document.getElementById(id);if(!el)return;el.classList.add('open');el.setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}
function pickerClose(id){const el=document.getElementById(id);if(!el)return;el.classList.remove('open');el.setAttribute('aria-hidden','true');if(!document.querySelector('.modal.open'))document.body.style.overflow=''}
function syncImmunizationPickerLabels(){
  const childId=document.getElementById('eventChild')?.value||'',vaccineId=document.getElementById('eventVaccine')?.value||'';
  const c=state.children.find(x=>x.id===childId),v=VACCINES.find(x=>x.id===vaccineId);
  const childBtn=document.getElementById('openChildPicker'),vaccineBtn=document.getElementById('openVaccinePicker');
  if(childBtn){childBtn.classList.toggle('selected',!!c);document.getElementById('eventChildLabel').textContent=c?c.name:'Pilih anak';document.getElementById('eventChildSub').textContent=c?`${c.parentName||'Orang tua'} • ${c.hamlet||c.village}`:'Tekan di sini untuk mencari'}
  if(vaccineBtn){vaccineBtn.disabled=!c;vaccineBtn.classList.toggle('selected',!!v);document.getElementById('eventVaccineLabel').textContent=v?v.label:'Pilih imunisasi';document.getElementById('eventVaccineSub').textContent=!c?'Pilih anak terlebih dahulu':v?'Tekan jika ingin mengganti':'Tekan untuk memilih dari daftar'}
}
function renderImmunizationReview(){
  const box=document.getElementById('immunizationReview'),btn=document.getElementById('saveImmunizationBtn');if(!box||!btn)return;
  const c=state.children.find(x=>x.id===document.getElementById('eventChild').value),v=VACCINES.find(x=>x.id===document.getElementById('eventVaccine').value),date=document.getElementById('eventDate').value,place=document.getElementById('eventServicePlace')?.value||'';
  const ready=!!(c&&v&&date);btn.disabled=!ready;
  if(!ready){box.innerHTML='<div class="review-empty"><span>✓</span><div><b>Periksa sebelum simpan</b><small>Pilih anak dan imunisasi. Ringkasannya akan muncul di sini.</small></div></div>';return}
  box.innerHTML=`<div class="review-ready"><div class="review-title">✓ Periksa sekali lagi</div><div class="review-grid"><div class="review-item"><span>Anak</span><b>${esc(c.name)}</b></div><div class="review-item"><span>Imunisasi</span><b>${esc(v.label)}</b></div><div class="review-item"><span>Orang tua</span><b>${esc(c.parentName||'-')}</b></div><div class="review-item"><span>Tanggal pelayanan</span><b>${esc(fullDate(date))}</b></div><div class="review-item"><span>Pos imunisasi</span><b>${esc(place||'Belum diisi')}</b></div><div class="review-item"><span>Tanggal input</span><b>Otomatis hari ini</b></div></div></div>`;
}
function openChildPicker(){
  const input=document.getElementById('childPickerSearch');if(input)input.value='';renderChildPickerResults('');pickerOpen('childPickerModal');setTimeout(()=>input?.focus(),120)
}
function renderChildPickerResults(query=''){
  const q=foldText(query.trim()),out=document.getElementById('childPickerResults');if(!out)return;
  let kids=[...state.children].filter(c=>!q||foldText([c.name,c.nik,c.parentName,c.hamlet,c.posyandu,c.village].join(' ')).includes(q));
  kids.sort((a,b)=>{const af=a.village===state.settings.focusVillage?0:1,bf=b.village===state.settings.focusVillage?0:1;if(af!==bf)return af-bf;const ae=latestEventTime(a.id),be=latestEventTime(b.id);if(!q&&ae!==be)return be.localeCompare(ae);return a.name.localeCompare(b.name,'id')});
  if(!kids.length){out.innerHTML='<div class="picker-empty"><b>Nama belum ditemukan</b>Coba ketik nama ibu, dusun, atau tekan “Tambah data anak”.</div>';return}
  out.innerHTML=kids.map(c=>{const ev=childEvents(c.id).sort((a,b)=>b.date.localeCompare(a.date))[0],sel=document.getElementById('eventChild').value===c.id;return `<button class="picker-option ${sel?'selected':''}" type="button" data-pick-child="${c.id}"><span class="option-icon">${esc(c.name.trim().charAt(0).toUpperCase()||'👶')}</span><span class="option-main"><b>${esc(c.name)}</b><small>${esc(c.parentName||'Orang tua belum diisi')} • ${esc(c.hamlet||'-')} • ${esc(c.posyandu||c.village)}</small>${ev?`<small>Terakhir: ${esc(getVaccine(ev.vaccineId).label)} • ${fmtDate(ev.date)}</small>`:''}</span>${sel?'<span class="option-state">Dipilih</span>':''}</button>`}).join('')
}
function chooseChild(id){const el=document.getElementById('eventChild');el.value=id;el.dispatchEvent(new Event('change',{bubbles:true}));prefillServicePlaceForChild(id);pickerClose('childPickerModal');document.getElementById('immunizationSuccess').hidden=true;setTimeout(()=>document.getElementById('openVaccinePicker')?.focus(),80)}
function openVaccinePicker(){const childId=document.getElementById('eventChild').value;if(!childId){openChildPicker();return}vaccinePickerFilter='missing';document.querySelectorAll('[data-vaccine-filter]').forEach(b=>b.classList.toggle('active',b.dataset.vaccineFilter==='missing'));const input=document.getElementById('vaccinePickerSearch');if(input)input.value='';renderVaccinePickerResults('');pickerOpen('vaccinePickerModal');setTimeout(()=>input?.focus(),120)}
function renderVaccinePickerResults(query=''){
  const childId=document.getElementById('eventChild').value,q=foldText(query.trim()),out=document.getElementById('vaccinePickerResults');if(!out)return;
  const counts={};const latest={};childEvents(childId).forEach(e=>{counts[e.vaccineId]=(counts[e.vaccineId]||0)+1;if(!latest[e.vaccineId]||e.date>latest[e.vaccineId])latest[e.vaccineId]=e.date});
  let items=VACCINES.filter(v=>!v.computed).filter(v=>vaccinePickerFilter==='all'||KOHORT_INPUT_IDS.includes(v.id)).filter(v=>!q||foldText(`${v.id} ${v.label}`).includes(q));
  if(vaccinePickerFilter==='missing'&&!q){const missing=items.filter(v=>!counts[v.id]);if(missing.length)items=missing}
  if(!items.length){out.innerHTML='<div class="picker-empty"><b>Tidak ditemukan</b>Coba kata lain atau pilih “Semua imunisasi”.</div>';return}
  const selected=document.getElementById('eventVaccine').value;
  out.innerHTML=items.map(v=>{const done=counts[v.id]||0;return `<button type="button" class="picker-option ${done?'done':''} ${selected===v.id?'selected':''}" data-pick-vaccine="${v.id}"><span class="option-icon">${done?'✓':esc(v.id.replaceAll('_','-').replace('DPT-HB-HIB','DPT').slice(0,5))}</span><span class="option-main"><b>${esc(v.label)}</b><small>${done?`Sudah tercatat ${done}x${latest[v.id]?' • terakhir '+fmtDate(latest[v.id]):''}`:'Belum tercatat untuk anak ini'}</small></span><span class="option-state">${selected===v.id?'Dipilih':done?'Sudah ada':'Pilih'}</span></button>`}).join('')
}
function chooseVaccine(id){const el=document.getElementById('eventVaccine');el.value=id;el.dispatchEvent(new Event('change',{bubbles:true}));pickerClose('vaccinePickerModal');setTimeout(()=>document.getElementById('eventDate')?.focus(),80)}
function showImmunizationSuccess(child,vaccine,date){const box=document.getElementById('immunizationSuccess');if(!box)return;box.hidden=false;box.innerHTML=`<div class="success-wrap"><span class="success-icon">✓</span><div><b>Data berhasil disimpan</b><p>${esc(child?.name||'-')} • ${esc(vaccine?.label||'-')} • ${esc(fullDate(date))}</p><div class="success-actions"><button class="btn primary" type="button" id="sameChildBtn">＋ Imunisasi lain, anak yang sama</button><button class="btn secondary" type="button" id="nextChildBtn">Anak berikutnya</button><button class="btn secondary" type="button" id="closeSuccessBtn">Selesai</button></div></div></div>`;box.scrollIntoView({behavior:'smooth',block:'center'});setTimeout(()=>{document.getElementById('sameChildBtn')?.addEventListener('click',()=>{box.hidden=true;document.getElementById('eventChild').value=child.id;document.getElementById('eventDate').value=date||today();prefillServicePlaceForChild(child.id);syncImmunizationPickerLabels();renderSelectedChild();openVaccinePicker()});document.getElementById('nextChildBtn')?.addEventListener('click',()=>{box.hidden=true;openChildPicker()});document.getElementById('closeSuccessBtn')?.addEventListener('click',()=>{box.hidden=true;showPage('home')})},0)}
function searchableLabel(select){return select?.options[select.selectedIndex]?.text||'Pilih'}
function initSearchableSelects(){SEARCHABLE_SELECT_IDS.forEach(id=>{const select=document.getElementById(id);if(!select||select.dataset.searchEnhanced)return;select.dataset.searchEnhanced='1';select.classList.add('searchable-select-native');const shell=document.createElement('div');shell.className='searchable-select-shell';select.parentNode.insertBefore(shell,select);shell.appendChild(select);const btn=document.createElement('button');btn.type='button';btn.className='searchable-select-button';btn.dataset.selectTarget=id;btn.innerHTML='<span></span>';shell.appendChild(btn);btn.addEventListener('click',()=>openGenericSelect(id));select.addEventListener('change',()=>refreshSearchableButtons())});refreshSearchableButtons()}
function refreshSearchableButtons(){SEARCHABLE_SELECT_IDS.forEach(id=>{const select=document.getElementById(id),btn=document.querySelector(`[data-select-target="${id}"]`);if(select&&btn){const span=btn.querySelector('span');if(span)span.textContent=searchableLabel(select)}})}
function genericSelectTitle(id){return ({childVillage:'Pilih desa anak',childVillageFilter:'Filter desa',riskVillageFilter:'Filter desa',eduVillage:'Pilih desa kegiatan',assessmentVillage:'Pilih desa peserta',reportVillageFilter:'Pilih desa laporan',settingFocusVillage:'Pilih desa fokus',childPosyandu:'Pilih Posyandu / pos utama',eventServicePlace:'Pilih Pos Imunisasi'})[id]||'Pilih data'}
function openGenericSelect(id){const select=document.getElementById(id);if(!select)return;genericSelectTarget=id;document.getElementById('genericSelectTitle').textContent=genericSelectTitle(id);const input=document.getElementById('genericSelectSearch');input.value='';renderGenericSelectResults('');pickerOpen('genericSelectModal');setTimeout(()=>input.focus(),120)}
function renderGenericSelectResults(query=''){const select=document.getElementById(genericSelectTarget),out=document.getElementById('genericSelectResults');if(!select||!out)return;const q=foldText(query),opts=[...select.options].filter(o=>!q||foldText(o.text).includes(q));out.innerHTML=opts.length?opts.map(o=>`<button type="button" class="picker-option ${o.value===select.value?'selected':''}" data-generic-option="${esc(o.value)}"><span class="option-icon">⌖</span><span class="option-main"><b>${esc(o.text)}</b></span>${o.value===select.value?'<span class="option-state">Dipilih</span>':''}</button>`).join(''):'<div class="picker-empty"><b>Tidak ditemukan</b>Coba ketik nama lain.</div>'}
function chooseGenericOption(value){const select=document.getElementById(genericSelectTarget);if(!select)return;select.value=value;select.dispatchEvent(new Event('change',{bubbles:true}));refreshSearchableButtons();pickerClose('genericSelectModal')}
function bindPickerEvents(){
  document.getElementById('openChildPicker')?.addEventListener('click',openChildPicker);document.getElementById('openVaccinePicker')?.addEventListener('click',openVaccinePicker);
  document.getElementById('childPickerSearch')?.addEventListener('input',e=>renderChildPickerResults(e.target.value));document.getElementById('vaccinePickerSearch')?.addEventListener('input',e=>renderVaccinePickerResults(e.target.value));document.getElementById('genericSelectSearch')?.addEventListener('input',e=>renderGenericSelectResults(e.target.value));
  document.getElementById('pickerAddChildBtn')?.addEventListener('click',()=>{pickerClose('childPickerModal');showPage('children');const c=document.getElementById('childFormCard');c.classList.add('open');document.getElementById('childFormTitle').textContent='Tambah Anak';setTimeout(()=>document.getElementById('childName')?.focus(),100)});
  document.querySelectorAll('[data-close-picker]').forEach(b=>b.addEventListener('click',()=>pickerClose(b.dataset.closePicker)));
  document.querySelectorAll('.picker-modal').forEach(m=>m.addEventListener('click',e=>{if(e.target===m)pickerClose(m.id)}));
  document.body.addEventListener('click',e=>{const c=e.target.closest('[data-pick-child]');if(c)chooseChild(c.dataset.pickChild);const v=e.target.closest('[data-pick-vaccine]');if(v)chooseVaccine(v.dataset.pickVaccine);const g=e.target.closest('[data-generic-option]');if(g)chooseGenericOption(g.dataset.genericOption);const f=e.target.closest('[data-vaccine-filter]');if(f){vaccinePickerFilter=f.dataset.vaccineFilter;document.querySelectorAll('[data-vaccine-filter]').forEach(x=>x.classList.toggle('active',x===f));renderVaccinePickerResults(document.getElementById('vaccinePickerSearch').value)}})
}

// Forms
const childForm=document.getElementById('childForm');
childForm.addEventListener('submit',async e=>{e.preventDefault();const id=document.getElementById('childId').value||uid('child');const obj={id,name:document.getElementById('childName').value.trim(),dob:document.getElementById('childDob').value,sex:document.getElementById('childSex').value,village:document.getElementById('childVillage').value,hamlet:document.getElementById('childHamlet').value.trim(),posyandu:document.getElementById('childPosyandu').value,nik:document.getElementById('childNik').value.trim(),parentName:document.getElementById('parentName').value.trim(),phone:document.getElementById('parentPhone').value.trim(),address:document.getElementById('childAddress').value.trim(),province:DEFAULT_AREA.province,district:DEFAULT_AREA.district,subdistrict:DEFAULT_AREA.subdistrict,puskesmas:DEFAULT_AREA.puskesmas,registeredAt:today()};const ix=state.children.findIndex(x=>x.id===id);if(ix>=0){const previous=state.children[ix];for(const k of ['province','district','subdistrict','puskesmas','registeredAt'])obj[k]=previous[k];state.children[ix]={...previous,...obj}}else state.children.push(obj);if(!await save('save_child'))return;childForm.reset();document.getElementById('childId').value='';document.getElementById('childFormCard').classList.remove('open');toast('Data anak berhasil disimpan')});
document.getElementById('cancelChildEdit').onclick=()=>{childForm.reset();document.getElementById('childId').value='';document.getElementById('childFormTitle').textContent='Tambah Anak';document.getElementById('childFormCard').classList.remove('open')};
document.getElementById('showChildFormBtn').onclick=()=>{const c=document.getElementById('childFormCard');c.classList.add('open');document.getElementById('childFormTitle').textContent='Tambah Anak';setTimeout(()=>c.scrollIntoView({behavior:'smooth',block:'start'}),50)};
document.getElementById('childSearch').addEventListener('input',renderChildren);document.getElementById('childVillageFilter').addEventListener('change',renderChildren);
document.getElementById('eventChild').addEventListener('change',()=>{document.getElementById('eventVaccine').value='';prefillServicePlaceForChild(document.getElementById('eventChild').value);renderSelectedChild();syncImmunizationPickerLabels();renderImmunizationReview()});
document.getElementById('eventVaccine').addEventListener('change',()=>{syncImmunizationPickerLabels();renderImmunizationReview()});
document.getElementById('eventDate').addEventListener('change',renderImmunizationReview);document.getElementById('eventServicePlace')?.addEventListener('change',renderImmunizationReview);
document.getElementById('useTodayBtn').addEventListener('click',()=>{document.getElementById('eventDate').value=today();renderImmunizationReview()});
document.getElementById('immunizationForm').addEventListener('submit',async e=>{e.preventDefault();const childId=document.getElementById('eventChild').value,vaccineId=document.getElementById('eventVaccine').value,date=document.getElementById('eventDate').value;if(!childId){openChildPicker();return}if(!vaccineId){openVaccinePicker();return}if(!date){toast('Pilih tanggal pelayanan terlebih dahulu');return}if(state.events.some(x=>x.childId===childId&&x.vaccineId===vaccineId&&x.date===date)&&!confirm('Imunisasi yang sama sudah pernah dicatat pada tanggal ini. Apakah Ibu yakin ingin menyimpan lagi?'))return;const child=state.children.find(x=>x.id===childId),vaccine=getVaccine(vaccineId);const servicePlace=document.getElementById('eventServicePlace')?.value||child?.posyandu||'';state.events.push({id:uid('event'),childId,vaccineId,date,inputDate:today(),servicePlace,nextDueDate:document.getElementById('eventNextDue').value,batch:document.getElementById('eventBatch').value.trim(),notes:document.getElementById('eventNotes').value.trim(),validated:state.settings.role!=='kader',createdAt:today()});if(!await save('save_immunization'))return;e.target.reset();document.getElementById('eventDate').value=today();fillServicePlaces();showImmunizationSuccess(child,vaccine,date);syncImmunizationPickerLabels();renderImmunizationReview();toast(`✓ ${child?.name||'Data'} berhasil disimpan`)});
document.getElementById('riskVillageFilter').addEventListener('change',()=>{selectedRiskHamlet='';renderFollowup()});document.getElementById('riskStatusFilter').addEventListener('change',renderFollowup);document.getElementById('trendVaccineSelect')?.addEventListener('change',renderCoverageTrend);
document.getElementById('educationForm').addEventListener('submit',async e=>{e.preventDefault();state.education.push({id:uid('edu'),date:document.getElementById('eduDate').value,type:document.getElementById('eduType').value,village:document.getElementById('eduVillage').value,hamlet:document.getElementById('eduHamlet').value.trim(),participants:Number(document.getElementById('eduParticipants').value),topic:document.getElementById('eduTopic').value,notes:document.getElementById('eduNotes').value.trim()});if(!await save('save_education'))return;e.target.reset();document.getElementById('eduDate').value=today();toast('Kegiatan edukasi tersimpan')});
document.getElementById('assessmentForm').addEventListener('submit',async e=>{e.preventDefault();state.assessments.push({id:uid('assess'),name:document.getElementById('assessmentName').value.trim(),type:document.getElementById('assessmentType').value,village:document.getElementById('assessmentVillage').value,date:document.getElementById('assessmentDate').value,pre:Number(document.getElementById('assessmentPre').value),post:Number(document.getElementById('assessmentPost').value)});if(!await save('save_assessment'))return;e.target.reset();document.getElementById('assessmentDate').value=today();toast('Nilai evaluasi tersimpan')});
document.getElementById('followupForm').addEventListener('submit',async e=>{e.preventDefault();state.followups.push({id:uid('fu'),childId:document.getElementById('followupChildId').value,outcome:document.getElementById('followupOutcome').value,date:document.getElementById('followupDate').value,notes:document.getElementById('followupNotes').value.trim()});if(!await save('save_followup'))return;document.getElementById('followupModal').classList.remove('open');toast('Hasil tindak lanjut tersimpan')});
document.getElementById('closeFollowupModal').onclick=()=>document.getElementById('followupModal').classList.remove('open');
document.getElementById('roleSelect').disabled=true;document.querySelector('.role-control > span').textContent='Peran';document.querySelectorAll('#roleSelect option').forEach(o=>o.textContent=o.textContent.replace('Uji: ',''));
document.getElementById('settingsForm').addEventListener('submit',async e=>{e.preventDefault();state.settings.puskesmas=document.getElementById('settingPuskesmas').value.trim();state.settings.year=Number(document.getElementById('settingYear').value);state.settings.focusVillage=document.getElementById('settingFocusVillage').value;state.settings.warningDays=Number(document.getElementById('settingWarningDays').value);if(!await save('save_settings'))return;toast('Filter tampilan diterapkan untuk sesi ini')});
document.getElementById('reportVillageFilter').addEventListener('change',renderReport);document.getElementById('reportMonthFilter').addEventListener('change',renderReport);
document.body.addEventListener('click',async e=>{const edit=e.target.closest('[data-edit-child]');if(edit){const c=state.children.find(x=>x.id===edit.dataset.editChild);if(!c)return;showPage('children');document.getElementById('childId').value=c.id;document.getElementById('childName').value=c.name;document.getElementById('childDob').value=c.dob;document.getElementById('childSex').value=c.sex;document.getElementById('childVillage').value=c.village;document.getElementById('childHamlet').value=c.hamlet;document.getElementById('childPosyandu').value=c.posyandu||'';document.getElementById('childNik').value=c.nik||'';document.getElementById('parentName').value=c.parentName;document.getElementById('parentPhone').value=c.phone||'';document.getElementById('childAddress').value=c.address||'';document.getElementById('childFormTitle').textContent='Ubah Data Anak';document.getElementById('childFormCard').classList.add('open');document.getElementById('childFormCard').scrollIntoView({behavior:'smooth',block:'start'})}
const qi=e.target.closest('[data-quick-immunize]');if(qi){showPage('immunization');document.getElementById('eventChild').value=qi.dataset.quickImmunize;document.getElementById('eventVaccine').value='';renderSelectedChild();syncImmunizationPickerLabels();renderImmunizationReview()}
const fu=e.target.closest('[data-followup]');if(fu){const c=state.children.find(x=>x.id===fu.dataset.followup);document.getElementById('followupChildId').value=c.id;document.getElementById('followupChildName').textContent=`${c.name} • ${c.parentName}`;document.getElementById('followupDate').value=today();document.getElementById('followupNotes').value='';document.getElementById('followupModal').classList.add('open')}
const va=e.target.closest('[data-validate]');if(va){const ev=state.events.find(x=>x.id===va.dataset.validate);if(ev){ev.validated=true;if(!await save('validate_event'))return;toast('Input berhasil divalidasi')}}
const rz=e.target.closest('[data-risk-hamlet]');if(rz){selectedRiskHamlet=selectedRiskHamlet===rz.dataset.riskHamlet?'':rz.dataset.riskHamlet;renderFollowup();setTimeout(()=>document.getElementById('followupList')?.scrollIntoView({behavior:'smooth',block:'start'}),40)}
if(e.target.closest('[data-risk-reset]')){selectedRiskHamlet='';renderFollowup()}});
function csvCell(v){if(typeof v==='string'&&/^[=+@\-\t\r]/.test(v))v="'"+v;return `"${String(v??'').replace(/"/g,'""')}"`}
function exportCsv(){
  const village=document.getElementById('reportVillageFilter').value||'all',month=Number(document.getElementById('reportMonthFilter').value||12),vaccines=VACCINES.filter(v=>v.excel);
  const h1=['NO','PUSKESMAS','DESA','SASARAN PUSDATIN','','','','','','SASARAN DAERAH','','','','','','HASIL IMUNISASI BAYI',...Array(Math.max(0,vaccines.length*6-1)).fill('')];
  const h2=['','','','BAYI BARU LAHIR','','','SURVIVING INFANTS','','','BAYI BARU LAHIR','','','SURVIVING INFANTS','','',...vaccines.flatMap(v=>[v.label,'','','','',''])];
  const h3=['','','','L','P','JUMLAH','L','P','JUMLAH','L','P','JUMLAH','L','P','JUMLAH',...vaccines.flatMap(()=>['# L','%','# P','%','# JML','%'])];
  const selected=village==='all'?state.targets:state.targets.filter(t=>t.name===village),rows=selected.map((t,i)=>excelRowData(t,i,month,false));if(village==='all')rows.push(excelRowData(aggregateTarget(state.targets),0,month,true));
  const csv='\ufeff'+[h1,h2,h3,...rows].map(r=>r.map(csvCell).join(',')).join('\r\n');download(csv,`SiMIDS_Format_Excel_${village}_${state.settings.year}_${String(month).padStart(2,'0')}.csv`,'text/csv;charset=utf-8')
}
const KOHORT_EXPORT_MAP=[
['HB0',['HB0','HB0_24','HB0_1_7','HB0_TOTAL']],['BCG 1',['BCG']],['POLIO 1',['OPV1']],['POLIO 2',['OPV2']],['POLIO 3',['OPV3']],['POLIO 4',['OPV4']],
['DPT-Hb-Hib 1',['DPT_HB_HIB1']],['DPT-Hb-Hib 2',['DPT_HB_HIB2']],['DPT-Hb-Hib 3',['DPT_HB_HIB3']],['IPV 1',['IPV1']],['IPV 2',['IPV2']],
['ROTA 1',['ROTA1']],['ROTA 2',['ROTA2']],['ROTA 3',['ROTA3']],['PCV 1',['PCV1']],['PCV 2',['PCV2']],['MR 1',['MR1']]
];
function kohortEvent(childId,ids){return [...state.events].filter(e=>e.childId===childId&&ids.includes(e.vaccineId)).sort((a,b)=>(b.date||'').localeCompare(a.date||''))[0]||null}
function exportIndividualKohort(){
  const headers=['NIK Anak','Nama Anak','Tanggal Lahir Anak','Jenis Kelamin Anak','Nama Orang Tua','Provinsi','Kabupaten atau Kota','Kecamatan','Kelurahan atau Desa','Puskesmas'];
  KOHORT_EXPORT_MAP.forEach(([label])=>headers.push(`Tanggal Imunisasi ${label}`,`Tanggal Input ${label}`,`Pos Imunisasi ${label}`));
  headers.push('Tanggal IDL 1','Tanggal Input IDL 1','Pos IDL 1','PKM Pembentuk IDL 1','Status IDL 1');
  const kids=[...state.children].sort((a,b)=>(a.name||'').localeCompare(b.name||'','id'));
  const rows=kids.map(c=>{
    const row=[c.nik||'',c.name||'',c.dob||'',c.sex==='L'?'Laki-laki':'Perempuan',c.parentName||'',c.province||DEFAULT_AREA.province,c.district||DEFAULT_AREA.district,c.subdistrict||DEFAULT_AREA.subdistrict,c.village||'',c.puskesmas||DEFAULT_AREA.puskesmas];
    KOHORT_EXPORT_MAP.forEach(([,ids])=>{const e=kohortEvent(c.id,ids);row.push(e?.date||'',e?.inputDate||'',e?.servicePlace||'')});
    row.push(c.idlDate||'',c.idlInputDate||'',c.idlPlace||'',c.idlPkm||'',c.idlStatus||'');
    return row;
  });
  const csv='\ufeff'+[headers,...rows].map(r=>r.map(csvCell).join(',')).join('\r\n');
  download(csv,`SiMIDS_Kohort_Individu_${today()}.csv`,'text/csv;charset=utf-8')
}
function download(data,name,type){const blob=new Blob([data],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),500)}
document.getElementById('exportReportBtn').onclick=exportCsv;document.getElementById('exportIndividualCsvBtn')?.addEventListener('click',exportIndividualKohort);document.getElementById('downloadBackupBtn').onclick=()=>download(JSON.stringify(state,null,2),`SiMIDS_Backup_${today()}.json`,'application/json');document.getElementById('importBackupInput').disabled=true;document.getElementById('resetDemoBtn').hidden=true;

const month=document.getElementById('reportMonthFilter');month.innerHTML=Array.from({length:12},(_,i)=>`<option value="${i+1}">${['Jan','Feb','Mar','Apr','Mei','Jun','Jul','Agu','Sep','Okt','Nov','Des'][i]}</option>`).join('');month.value=new Date().getMonth()+1;document.getElementById('eventDate').value=today();document.getElementById('eduDate').value=today();document.getElementById('assessmentDate').value=today();document.getElementById('followupDate').value=today();
if('serviceWorker'in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('./sw.js').catch(()=>{});
renderAll();
initSearchableSelects();
bindPickerEvents();
syncImmunizationPickerLabels();
renderImmunizationReview();
maybeShowDailyReminder();

window.SIMIDS_READY=true;const accountTools=document.createElement('div');accountTools.style.cssText='display:flex;gap:8px;padding:8px;flex-wrap:wrap';accountTools.innerHTML='<button type=button id=reloadCloud class=mini-btn>Muat ulang data</button><button type=button id=logoutCloud class=mini-btn>Keluar</button>';document.querySelector('.side-intro').appendChild(accountTools);document.getElementById('reloadCloud').onclick=()=>location.reload();document.getElementById('logoutCloud').onclick=()=>SimidsBackend.logout();
